---
version: 2
title: Create, rollout and delete deployment with random name
subtasks:
- title: Run a single workload with create/rollout/delete deployment
  scenario:
    Kubernetes.create_rollout_and_delete_deployment:
      image: busybox
      replicas: 1
      command:
      - sleep
      - $SLEEPTIME
      env:
      - name: "SLEEPTIME"
        value: "3600"
      changes:
        env:
        - name: "SLEEPTIME"
          value: "4800"
  runner:
    constant:
      concurrency: 2
      times: 10
  contexts:
    namespaces:
      count: 3
      with_serviceaccount: true
- title: Run create/rollout/delete deployment with rps runner
  scenario:
    Kubernetes.create_rollout_and_delete_deployment:
      image: busybox
      replicas: 1
      command:
      - sleep
      - $SLEEPTIME
      env:
      - name: "SLEEPTIME"
        value: "3600"
      changes:
        env:
        - name: "SLEEPTIME"
          value: "4800"
  runner:
    rps:
      rps: 2
      times: 10
  contexts:
    namespaces:
      count: 3
      with_serviceaccount: true
