---
  Kubernetes.create_check_and_delete_emptydir_volume:
  -
    args:
      image: nginx
      mount_path: /opt/check
      check_cmd:
      - ls
      - /opt/check
      sleep_time: 1
      retries_total: 40
    runner:
      type: constant
      concurrency: 2
      times: 10
    context:
      kubernetes.namespaces:
        count: 3
        with_serviceaccount: yes
    sla:
      failure_rate:
        max: 0
  -
    args:
      image: nginx
      mount_path: /opt/check
      check_cmd:
      - ls
      - /opt/check
      sleep_time: 1
      retries_total: 40
    runner:
      type: rps
      rps: 2
      times: 10
    context:
      kubernetes.namespaces:
        count: 3
        with_serviceaccount: yes
    sla:
      failure_rate:
        max: 0
