---
  Kubernetes.create_delete_namespace:
  -
    args:
      sleep_time: 1
      retries_total: 50
    runner:
      type: rps
      times: 6
      rps: 3
    sla:
      failure_rate:
        max: 0
  -
    args:
      sleep_time: 1
      retries_total: 30
    runner:
      type: constant
      times: 4
      concurrency: 4
    sla:
      failure_rate:
        max: 0